apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stackiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migrate
          image: jethroservergit.duckdns.org/stackiq-team/backend:1.0.19 # {"$imagepolicy": "flux-system:backend"}
          command: ["npx", "prisma", "migrate", "deploy", "--config", "prisma.config.js"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: DATABASE_URL
      imagePullSecrets:
        - name: gitea-registry
      containers:
        - name: backend
          image: jethroservergit.duckdns.org/stackiq-team/backend:1.0.19 # {"$imagepolicy": "flux-system:backend"}
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: REDIS_URL
            - name: BULLMQ_QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: BULLMQ_QUEUE_NAME
            - name: GITHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: GITHUB_API_TOKEN
            - name: WORKER_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: WORKER_CONCURRENCY
            - name: EXPLORE_TOP_LIMIT
              valueFrom:
                secretKeyRef:
                  name: stackiq-secrets
                  key: EXPLORE_TOP_LIMIT
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stackiq
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
