apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      containers:
        - name: runner
          image: gitea/act_runner:latest
          env:
            - name: GITEA_INSTANCE_URL
              value: "https://jethroservergit.duckdns.org"
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-secret
                  key: token
            - name: GITEA_RUNNER_NAME
              value: "k8s-runner"
            - name: CONFIG_FILE
              value: /config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: gitea-runner-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-config
  namespace: gitea-runner
data:
  config.yaml: |
    runner:
      capacity: 2
    container:
      network: host
      options: --add-host=jethroservergit.duckdns.org:192.168.0.50
    host:
      workdir_parent: /tmp/act