apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitea-charts
  namespace: flux-system
spec:
  interval: 24h
  url: https://dl.gitea.com/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 12h
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: jethroservergit.duckdns.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - jethroservergit.duckdns.org
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        email: jethroroy@gmail.com
      config:
        actions:
          ENABLED: true
        packages:
          MAX_CREATION_LIMIT: 0
          CHUNKED_UPLOAD_SIZE: 104857600
    service:
      http:
        type: ClusterIP
